package com.xzz.hxjdglpt.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig friendDaoConfig;
    private final DaoConfig groupsDaoConfig;
    private final DaoConfig groupMemberDaoConfig;

    private final FriendDao friendDao;
    private final GroupsDao groupsDao;
    private final GroupMemberDao groupMemberDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends
            AbstractDao<?, ?>>, DaoConfig> daoConfigMap) {
        super(db);

        friendDaoConfig = daoConfigMap.get(FriendDao.class).clone();
        friendDaoConfig.initIdentityScope(type);

        groupsDaoConfig = daoConfigMap.get(GroupsDao.class).clone();
        groupsDaoConfig.initIdentityScope(type);

        groupMemberDaoConfig = daoConfigMap.get(GroupMemberDao.class).clone();
        groupMemberDaoConfig.initIdentityScope(type);


        friendDao = new FriendDao(friendDaoConfig, this);
        groupsDao = new GroupsDao(groupsDaoConfig, this);
        groupMemberDao = new GroupMemberDao(groupMemberDaoConfig, this);

        registerDao(Friend.class, friendDao);
        registerDao(Groups.class, groupsDao);
        registerDao(GroupMember.class, groupMemberDao);
    }

    public void clear() {
        friendDaoConfig.getIdentityScope().clear();
        groupsDaoConfig.getIdentityScope().clear();
        groupMemberDaoConfig.getIdentityScope().clear();
    }

    public FriendDao getFriendDao() {
        return friendDao;
    }


    public GroupsDao getGroupsDao() {
        return groupsDao;
    }


    public GroupMemberDao getGroupMemberDao() {
        return groupMemberDao;
    }

}
