package com.xzz.hxjdglpt.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table GROUPS.
 */
public class Groups {
    private String id;
    private String name;
    private String portraitUri;
    private String creator;

    public Groups(String id) {
        this.id = id;
    }

    public Groups(String id, String name, String creator, String portraitUri) {
        this.id = id;
        this.name = name;
        this.creator = creator;
        this.portraitUri = portraitUri;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPortraitUri() {
        return portraitUri;
    }

    public void setPortraitUri(String portraitUri) {
        this.portraitUri = portraitUri;
    }

    public String getCreator() {
        return creator;
    }

    public void setCreator(String creator) {
        this.creator = creator;
    }

}
